package helpers

import slick.jdbc.H2Profile.api._
import scala.concurrent.{Future, ExecutionContext, Await}
import scala.concurrent.duration._

/**
 * Helper class for managing the H2 test database.
 * Creates tables and provides methods for inserting test data.
 */
object TestDatabaseHelper {

  def createDatabase()(implicit ec: ExecutionContext): Database = {
    Database.forURL(
      url = "jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE",
      driver = "org.h2.Driver",
      user = "sa",
      password = ""
    )
  }

  def createTables(db: Database)(implicit ec: ExecutionContext): Future[Unit] = {
    val createUsersTable = sqlu"""
      CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR(255) NOT NULL,
        password VARCHAR(255) NOT NULL
      )
    """

    val createBooksTable = sqlu"""
      CREATE TABLE IF NOT EXISTS books (
        isbn VARCHAR(255) PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        author VARCHAR(255) NOT NULL,
        publish_year INT,
        pages INT,
        cover VARCHAR(1024)
      )
    """

    val createPublicationsTable = sqlu"""
      CREATE TABLE IF NOT EXISTS publications (
        doi VARCHAR(255) PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        authors VARCHAR(255) NOT NULL,
        publish_year INT,
        pages VARCHAR(50),
        cover VARCHAR(1024)
      )
    """

    val createEntriesTable = sqlu"""
      CREATE TABLE IF NOT EXISTS entries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        entry_type VARCHAR(50) NOT NULL,
        ref_id VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        status VARCHAR(50) DEFAULT 'to_read',
        pages_read INT DEFAULT 0,
        alt_cover VARCHAR(1024) DEFAULT '',
        series VARCHAR(255),
        tags VARCHAR(1024) DEFAULT '',
        finished_at DATE
      )
    """

    val createNotesTable = sqlu"""
      CREATE TABLE IF NOT EXISTS notes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        entry_id BIGINT NOT NULL,
        user_id BIGINT NOT NULL,
        title VARCHAR(255) NOT NULL,
        content TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_note_entry FOREIGN KEY (entry_id) REFERENCES entries(id) ON DELETE CASCADE
      )
    """

    db.run(DBIO.seq(
      createUsersTable,
      createBooksTable,
      createPublicationsTable,
      createEntriesTable,
      createNotesTable
    ))
  }

  def cleanTables(db: Database)(implicit ec: ExecutionContext): Future[Unit] = {
    db.run(DBIO.seq(
      sqlu"DELETE FROM notes",
      sqlu"DELETE FROM entries",
      sqlu"DELETE FROM books",
      sqlu"DELETE FROM publications",
      sqlu"DELETE FROM users"
    ))
  }

  def insertTestUser(db: Database, id: Long, username: String, password: String = "test")(implicit ec: ExecutionContext): Future[Int] = {
    db.run(sqlu"INSERT INTO users (id, username, password) VALUES ($id, $username, $password)")
  }

  def insertTestBook(db: Database, isbn: String, title: String, author: String, publishYear: Int = 2020, pages: Int = 200, cover: String = "")(implicit ec: ExecutionContext): Future[Int] = {
    db.run(sqlu"INSERT INTO books (isbn, title, author, publish_year, pages, cover) VALUES ($isbn, $title, $author, $publishYear, $pages, $cover)")
  }

  def insertTestEntry(db: Database, userId: Long, entryType: String, refId: String)(implicit ec: ExecutionContext): Future[Int] = {
    db.run(sqlu"INSERT INTO entries (user_id, entry_type, ref_id) VALUES ($userId, $entryType, $refId)")
  }

  def setupTestData(db: Database)(implicit ec: ExecutionContext): Future[Unit] = {
    for {
      _ <- insertTestUser(db, 0L, "guest", "")
      _ <- insertTestUser(db, 1L, "testuser", "password123")
      _ <- insertTestBook(db, "9780141036144", "1984", "George Orwell", 1949, 328, "")
      _ <- insertTestBook(db, "9780060935467", "To Kill a Mockingbird", "Harper Lee", 1960, 281, "")
      _ <- insertTestEntry(db, 1L, "book", "9780141036144")
      _ <- insertTestEntry(db, 1L, "book", "9780060935467")
    } yield ()
  }
}
